on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.34'
      - name: Test by deno run command
        continue-on-error: true
        run: |
          cd deno
          deno task compile
          mv textlint ../deno-compile/
          chmod +x ../deno-compile/textlint
      - uses: actions/upload-artifact@v3
        with:
          name: binary
          path: deno-compile
  releases:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: binary
          path: deno-compile
      - name: Create release on GitHub
        id: create-release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ''
          draft: false
      - run: |
          ls -lR
      - name: Upload binary to GitHub
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: deno-compile/textlint
          asset_name: textlint
          asset_content_type: application/octet-stream
